server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:mem:loans
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - application_qa.yml
      - application_prod.yml
  #    To activate a profile, uncomment the line below
  #    We use the "active" property to activate a profile
  profiles:
    active: qa

build:
  version: "3.0"

loans:
  message: "Welcome to the Loans Microservice local API"
  contactDetails:
    name: "Ilbert Castillo"
    email: "ilbert@gmail.com"
  onCallSupport:
    - (849) 555-1212
    - (849) 555-1213