spring:
  config:
    activate:
      on-profile: qa

build:
  version: "2.0"

loans:
  message: "Welcome to the Loans Microservice QA"
  contactDetails:
    name: "Ilbert Castillo QA"
    email: "ilbert@gmail.com"
  onCallSupport:
    - (849) 555-3333
    - (849) 555-4444